# a mybinder.org-ready environment for demoing loops
# this environment may also be used locally on Linux/MacOS/Windows, e.g.
#
#   conda env update --file binder/environment.yml
#   conda activate loops-demo
#
name: loops-demo

channels:
  - conda-forge

dependencies:
  # runtime dependencies
  - python >=3.10,<3.11.0a0
  - jupyterlab >=4.0.0,<5
  # labextension build dependencies
  - nodejs >=18,<19
  - pip
  - wheel
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - python-duckdb==0.6.1
  - scikit-learn
  - yellowbrick
  - mscorefonts
  # additional packages for demos
  # - ipywidgets
